#pragma once

enum Constants
{
	kMagicMomentOwnerIdSize = 8,
	kShapeshifterPartNameSize = 7,
	kMagicMomentNameSize = 15,
	kSecretCodeLength = 12,
	kMoneyCap = 65535,
	kQuestSwapForceBadguyBasherBits = 10,
	kQuestSwapForceFruitFrontiersmanBits = 4,
	kQuestSwapForceFlawlessChallengerBits = 1,
	kQuestSwapForceTrueGladiatorBits = 4,
	kQuestSwapForceTotallyMaxedOutBits = 1,
	kQuestSwapForceElementalistBits = 13,
	kQuestSwapForceElemental1Bits = 8,
	kQuestSwapForceElemental2Bits = 9,
	kQuestSwapForceIndividualBits = 16,
	kQuestGiantsMonsterMasherBits = 10,
	kQuestGiantsBattleChampBits = 4,
	kQuestGiantsChowHoundBits = 5,
	kQuestGiantsHeroicChallengerBits = 1,
	kQuestGiantsArenaArtistBits = 1,
	kQuestGiantsElementalistBits = 13,
	kQuestGiantsEarthStonesmithBits = 5,
	kQuestGiantsEarthWreckerBits = 5,
	kQuestGiantsWaterExtinguisherBits = 1,
	kQuestGiantsWaterWaterfallBits = 4,
	kQuestGiantsAirSkyLooterBits = 9,
	kQuestGiantsAirFromAboveBits = 5,
	kQuestGiantsFireBombardierBits = 5,
	kQuestGiantsFireSteamerBits = 1,
	kQuestGiantsLifeFullyStockedBits = 8,
	kQuestGiantsLifeMelonMaestroBits = 8,
	kQuestGiantsUndeadByAThreadBits = 1,
	kQuestGiantsUndeadBossedAroundBits = 2,
	kQuestGiantsMagicPuzzlePowerBits = 5,
	kQuestGiantsMagicWarpWomperBits = 1,
	kQuestGiantsTechMagicIsntMightBits = 6,
	kQuestGiantsTechCrackerBits = 5,
	kQuestGiantsIndividualBits = 16,
	kDriverQuestTrackBits = 2,
	kDriverQuestStepBits = 3,
	kDriverQuestObjectiveBits = 6
};