#pragma once

#include <cstdint>

enum Constants
{
	kMagicMomentOwnerIdSize = 8,
	kShapeshifterPartNameSize = 7,
	kMagicMomentNameSize = 15,
	kSecretCodeLength = 12,
	kMoneyCap = 65535,
	kQuestSwapForceBadguyBasherBits = 10,
	kQuestSwapForceFruitFrontiersmanBits = 4,
	kQuestSwapForceFlawlessChallengerBits = 1,
	kQuestSwapForceTrueGladiatorBits = 4,
	kQuestSwapForceTotallyMaxedOutBits = 1,
	kQuestSwapForceElementalistBits = 13,
	kQuestSwapForceElemental1Bits = 8,
	kQuestSwapForceElemental2Bits = 9,
	kQuestSwapForceIndividualBits = 16,
	kQuestGiantsMonsterMasherBits = 10,
	kQuestGiantsBattleChampBits = 4,
	kQuestGiantsChowHoundBits = 6,
	kQuestGiantsHeroicChallengerBits = 1,
	kQuestGiantsArenaArtistBits = 1,
	kQuestGiantsElementalistBits = 13,
	kQuestGiantsEarthStonesmithBits = 5,
	kQuestGiantsEarthWreckerBits = 5,
	kQuestGiantsWaterExtinguisherBits = 1,
	kQuestGiantsWaterWaterfallBits = 5,
	kQuestGiantsAirSkyLooterBits = 9,
	kQuestGiantsAirFromAboveBits = 5,
	kQuestGiantsFireBombardierBits = 5,
	kQuestGiantsFireSteamerBits = 1,
	kQuestGiantsLifeFullyStockedBits = 8,
	kQuestGiantsLifeMelonMaestroBits = 8,
	kQuestGiantsUndeadByAThreadBits = 1,
	kQuestGiantsUndeadBossedAroundBits = 2,
	kQuestGiantsMagicPuzzlePowerBits = 5,
	kQuestGiantsMagicWarpWomperBits = 1,
	kQuestGiantsTechMagicIsntMightBits = 6,
	kQuestGiantsTechCrackerBits = 5,
	kQuestGiantsIndividualBits = 16,
	kDriverQuestTrackBits = 2,
	kDriverQuestStepBits = 3,
	kDriverQuestObjectiveBits = 6,
	kExperienceLevel01 = 0,
	kExperienceLevel02 = 1000,
	kExperienceLevel03 = 2200,
	kExperienceLevel04 = 3800,
	kExperienceLevel05 = 6000,
	kExperienceLevel06 = 9000,
	kExperienceLevel07 = 13000,
	kExperienceLevel08 = 18200,
	kExperienceLevel09 = 24800,
	kExperienceLevel10 = 33000,
	kExperienceLevel11 = 42700,
	kExperienceLevel12 = 53900,
	kExperienceLevel13 = 66600,
	kExperienceLevel14 = 80800,
	kExperienceLevel15 = 96500,
	kExperienceLevel16 = 113700,
	kExperienceLevel17 = 132400,
	kExperienceLevel18 = 152600,
	kExperienceLevel19 = 174300,
	kExperienceLevel20 = 197500,
	kExperienceLevelCount = 20,
};

extern const uint32_t experienceForLevelMap[kExperienceLevelCount];