#include "kTfbSpyroTag_HatType.hpp"

const char* hatNames_en[kTfbSpyroTag_Hat_MAX + 1] = {
	"None",
	"Combat Hat",
	"Napoleon Hat",
	"Spy Gear",
	"Miner Hat",
	"General's Hat",
	"Pirate Hat",
	"Propellor Cap",
	"Coonskin Cap",
	"Straw Hat",
	"Fancy Hat",			//Hat 10: Sunday
	"Top Hat",
	"Viking Helmet",
	"Spiked Hat",
	"Anvil Hat",
	"Beret",
	"Birthday Hat",
	"Bone Head",
	"Bowler Hat",
	"Wabbit Ears",
	"Tropical Turban",		//Hat 20: Carmen
	"Chef Hat",
	"Cowboy Hat",
	"Rocker Hair",
	"Royal Crown",
	"Lil Devil",
	"Eye Hat",
	"Fez",
	"Crown of Light",
	"Jester Hat",
	"Winged Hat",			//Hat 30: Mercury
	"Moose Hat",
	"Plunger Head",
	"Pan Hat",
	"Rocket Hat",
	"Santa Hat",
	"Tiki Hat",
	"Trojan Helmet",
	"Unicorn Hat",
	"Wizard Hat (Spyro's Adventure)",
	"Pumpkin Hat",			//Hat 40: Pumpkin
	"Pirate Doo Rag",
	"Cossack Hat",
	"Flower Hat",
	"Balloon Hat",
	"Happy Birthday!",
	//2012 Start
	"Vintage Baseball Cap",
	"Hat 47",				//They skipped this one
	"Bowling Pin Hat",
	"Officer Cap",
	"Firefighter Helmet",	//Hat 50: FirefighterHelmet
	"Graduation Hat",
	"Lampshade Hat",
	"Mariachi Hat",
	"Hat 54",				//They skipped this one
	"Paper Fast Food Hat",
	"Pilgrim Hat",
	"Police Siren Hat",
	"Purple Fedora",
	"Archer Hat",
	"Hat 60",				//Hat 60: They skipped this one
	"Safari Hat",
	"Sailor Hat",
	"Hat 63",				//They skipped this one
	"Dancer Hat",
	"Traffic Cone Hat",
	"Turban",
	"Battle Helmet",
	"Bottle Cap Hat",
	"Hat 69",
	"Carrot Hat",			//Hat 70: Carrot
	"Hat 71",				//They skipped this one
	"Elf Hat",
	"Fishing Hat",
	"Future Hat",
	"Nefertiti",
	"Hat 76",				//They skipped this one
	"Pants Hat",
	"Princess Hat",
	"Toy Soldier Hat",
	"Trucker Hat",			//Hat 80: Trucker
	"Umbrella Hat",
	"Showtime Hat",
	"Ceasar Hat",
	"Flower Fairy Hat",
	"Funnel Hat",
	"Scrumshanks Hat",
	"Biter Hat",
	"Atom Hat",
	"Sombrero",
	"Rasta Hat",			//Hat 90: Rasta
	"Kufi Hat",
	"Knight Helm",
	"Dangling Carrot Hat",
	"Bronze Top Hat",
	"Silver Top Hat",
	"Gold Top Hat",
	//2013 Start
	"Rain Hat",
	"The Outsider",
	"Greeble Hat",
	"Volcano Hat",			//Hat 100: Volcano
	"Boater Hat",
	"Stone Hat",
	"Stovepipe Hat",
	"Boonie Hat",
	"Sawblade Hat",
	"Zombeanie Hat",
	"Gaucho Hat",
	"Roundlet Hat",
	"Capuchon",
	"Tricorn Hat",			//Hat 110: Tricorn
	"Feathered Headdress",	//Double check the name
	"Bearskin Cap",
	"Fishbone Hat",
	"Ski Cap",
	"Crown of Frost",
	"Four Winds Hat",
	"Beacon Hat",
	"Flower Garland",
	"Tree Branch",
	"Aviator's Cap",		//Hat 120: AviatorsCap
	"Asteroid Hat",
	"Crystal Hat",
	"Creepy Helm",
	"Fancy Ribbon",
	"Deely Boppers",
	"Beanie",
	"Leprechaun Hat",
	"Shark Hat",
	"Life Preserver Hat",
	"Glittering Tiara",		//Hat 130: GlitteringTiara
	"Great Helm",
	"Space Helmet",
	"UFO Hat",
	"Whirlwind Diadem",
	"Obsidian Helm",
	"Lilypad Hat",
	"Crown of Flames",
	"Runic Headband",
	"Clockwork Hat",
	"Cactus Hat",			//Hat 140: CactusHat
	"Skullhelm",
	"Gloop Hat",
	"Puma Hat",
	"Elephant Hat",
	"Tiger Skin Cap",
	"Teeth Top Hat",
	"Turkey Hat",
	"Eyefro",
	"Bacon Bandana",
	"Awesome Hat",			//Hat 150: AwesomeHat
	"Card Shark Hat",
	"Springtime Hat",
	"Jolly Hat",
	"Kickoff Hat",
	//2014 Hat
	"Beetle Hat",
	"Brain Hat",
	"Brainiac Hat",
	"Bucket Hat",
	"Desert Crown",
	"Ceiling Fan Hat",		//Hat 160: Fan
	"Imperial Hat",
	"Clown Classic Hat",
	"Clown Bowler Hat",
	"Colander Hat",
	"Kepi Hat",
	"Cornucopia Hat",
	"Cubano Hat",
	"Cycling Hat",
	"Daisy Crown",
	"Dragon Skull",			//Hat 170: Skull
	"Outback Hat",
	"Lil' Elf Hat",
	"Generalissimo",
	"Garrison Hat",
	"Gondolier Hat",
	"Hunting Hat",
	"Juicer Hat",
	"Kokoshnik",
	"Medic Hat",
	"Melon Hat",			//Hat 180: Melon
	"Mountie Hat",
	"Nurse Hat",
	"Palm Hat",
	"Paperboy Hat",
	"Parrot Nest",
	"Old-Time Movie Hat",
	"Classic Pot Hat",
	"Radar Hat",
	"Crazy Light Bulb Hat",
	"Rubber Glove Hat",		//Hat 190: RubberGlove
	"Rugby Hat",
	"Sharkfin Hat (Shark Hat)",
	"Sleuth Hat",
	"Shower Cap",
	"Bobby",
	"Hedgehog Hat",
	"Steampunk Hat",
	"Flight Attendant Hat",
	"Monday Hat",
	"Sherpa Hat",		//Hat 200: Tibet
	"Trash Lid",
	"Turtle Hat",
	"Extreme Viking Hat",
	"Scooter Hat",
	"Volcano Island Hat",
	"Synchronized Swimming Cap",
	"William Tell Hat",
	"Tribal Hat",
	"Rude Boy Hat",
	"Pork Pie Hat",		//Hat 210: PorkPieChecker
	"Alarm Clock Hat",
	"Batter Up Hat",
	"Horns Be With You",
	"Croissant Hat",
	"Weather Vane Hat",
	"Rainbow Hat",
	"Eye of Kaos Hat",
	"Bat Hat",
	"Light Bulb",
	"Firefly Jar",		//Hat 220: Fireflies
	"Shadow Ghost Hat",
	"Lighthouse Beacon Hat",
	"Tin Foil Hat",
	"Night Cap",
	"Storm Hat",
	"Gold Arkeyan Helm",
	"Toucan Hat",
	"Pyramid Hat",
	"Miniature Skylands Hat",
	"Wizard Hat (Trap Team)",	//Hat 230: Wizard02, also called Sorcerer
	"Hat 231",
	"Candy Cane Hat",
	"Eggshell Hat",
	"Candle Hat",
	"Dark Helm",
	"Planet Hat",
	"Bellhop Hat",
	"Bronze Arkeyan Helm",
	"Silver Arkeyan Helm",
	"Raver Hat",				//Hat 240: Raver
	"Shire Hat",
	"Mongol Hat",
	"Skipper Hat",
	"Medieval Bard Hat",
	"Wooden Hat",
	"Carnival Hat",
	"Coconut Hat",
	"Model Home Hat",
	"Ice Cream Hat",
	"Molekin Mountain Hat",		//Hat 250: Molekin
	"Sheepwrecked Hat",
	"Core of Light Hat",
	"Octavius Cloptimus Hat",
	"Hat 254",
	"Hat 255",
	"Hat 256",
	"Hat 257",
	"Hat 258",
	"Hat 259",
	//2015 Start
	"Dive Bomber Hat",			//Hat 260: DiveBomber
	"Sea Shadow Hat",
	"Burn-Cycle Header",
	"Reef Ripper Helmet",
	"Jet Stream Helmet",
	"Soda Skimmer Shower Cap",
	"Tomb Buggy Skullcap",
	"Stealth Stinger Beanie",
	"Shark Tank Topper",
	"Gold Rusher Cog Cap",
	"Splatter Splasher Spires",	//Hat 270: SplatterSplasher
	"Thump Trucker's Hat",
	"Buzz Wing Hat",
	"Shield Striker Helmet",
	"Sun Runner Spikes",
	"Hot Streak Headpiece",
	"Sky Slicer Hat",
	"Crypt Crusher Cap",
	"Mags Hat",
	"Kaos Krown",
	"Eon's Helm"				//Hat 280: EonHelm
};